### ISSUE TITLE
`zext.w` should not exist in `Zba` group

### ISSUE THREAD

**Issue by LeeKaiXuan** [riscv/riscv-isa-manual#1350] opened 2024-04-17 02:21 UTC
Hi, I saw `zext.w rd, rs` was listed in table of Zba extension. However, in ratified version (RISC-V Bit-Manipulation ISA-extensions November 2021), Zba extension should only have 8 instructions without `zext.w`. It seem is a typo and should be removed from the table.
### Current version:
![image](https://github.com/riscv/riscv-isa-manual/assets/39395688/c62a08df-73aa-4653-8723-0fee75359f25)
### Ratified version:
![image](https://github.com/riscv/riscv-isa-manual/assets/39395688/8d92e52b-977e-43a9-a01a-168f34b6cbac)

**Comment by aswaterman** [comment] 2024-04-17 02:50
Duplicate of #1321, resolved by https://github.com/riscv/riscv-isa-manual/commit/7cbf1dcf6ea84958b29a1ce60e9c95a349feb7e7

**Closed by aswaterman** 2024-04-17 02:50 UTC

**Comment by KrystalDelusion** [comment] 2024-10-03 08:12
https://github.com/riscv/riscv-isa-manual/commit/7cbf1dcf6ea84958b29a1ce60e9c95a349feb7e7 appears to have been reverted at some point, was this intentional?
